Vagrant.configure("2") do |config|
  
  config.vm.box = "centos/7"

  config.vm.define "sso" do |sso|

    sso.vm.network "forwarded_port", guest: 8080, host: 8080
    sso.vm.network "forwarded_port", guest: 9990, host: 9990
    
    sso.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end

    sso.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook-sso.yml"
    end

  end 


  config.vm.define "streams" do |streams|

    streams.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end

    streams.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook-streams.yml"
    end

  end



  
end
